<?php

/**
 * Implements hook_menu().
 * @return array Menu items
 */
function sprbs_menu() {
  $items = array();

  $items['admin/config/sp'] = array(
    'title'            => 'SP',
    'description'      => 'SP-specifieke instellingen',
    'weight'           => -8,
    'access callback'  => 'user_access',
    'access argument'  => array('administer site configuration'),
   );

  return $items;
}
